name: CI

on:
  pull_request: {}
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with: { ruby-version: "3.2", bundler-cache: true }
      - run: bundle exec standardrb

  test:
    runs-on: ubuntu-latest
    services:
      postgres: { image: postgres:14, ports: ["5432:5432"], env: { POSTGRES_PASSWORD: "postgres" } }
    
    strategy:
      matrix: { ruby: ["3.1", "3.2", "3.3"] }
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with: { ruby-version: ${{ matrix.ruby }}, bundler-cache: true }
      
      - name: Setup DB
        env: { DATABASE_URL: "postgres://postgres:postgres@localhost:5432/test" }
        run: |
          bundle exec rake db:create
          bundle exec rake db:migrate
      
      - run: bundle exec rspec